server:
  forward-headers-strategy: native
spring:
  profiles:
    active: local

  datasource:
    url: jdbc:mysql://inha-pj-09-rds.cj24wem202yj.us-east-1.rds.amazonaws.com:3306/emotion_diary
    username: admin
    password: inhateam9
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        use_sql_comments: true
        enable_lazy_load_no_trans: true
        jdbc:
          lob:
            non_contextual_creation: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1041447353700-ck5s40n1e4ua81tln06a10cas4pred83.apps.googleusercontent.com
            client-secret: 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
            client-name: Google
            scope: "openid,profile,email,https://www.googleapis.com/auth/calendar.events"

        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://www.googleapis.com/oauth2/v4/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

cloud:
  aws:
    region:
      static: us-east-1

management:
  endpoints: # endpoint가 아니라 endpoints
    web:
      base-path: /actuator
      exposure:
        include: health,info # 노출할 엔드포인트 명시
  endpoint:
    health:
      show-details: when-authorized # 헬스체크 상세 정보 표시 조건
  health:
    db:
      enabled: true # DB 헬스체크 활성화

jwt:
  secret: 8a620a6cb951f5072105c91b9aec1a0399f3363712f729f04804f14379c07c5d5e70fdd28f807d3a4a2b59f23f7a0d9d28d91c924fafc7688426f8fdf1a5ed20

frontend:
  url: https://withudiary.my

openai:
  api-key: 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
  model: gpt-3.5-turbo
  max-tokens: 1000
  temperature: 0.7
  timeout:
    connect: 30000
    read: 30000
    write: 30000
